connection:
  username: "${USER}"
  auth_type: "keypair"
  auth:
    keypair: "/home/${USER}/.ssh/id_rsa"
deployment:
  cluster_name: "eloqkv_with_multiple_ng"
  product: "EloqKV"
  version: "debug"
  install_dir: "/home/${USER}"
  tx_service:
    tx_host_ports: [192.168.122.24:6379,192.168.122.25:6379,192.168.122.26:6379]
  # storage_service:
  #   rocksdb: !LOCAL
  #     # path: /tmp
