connection:
  username: "${USER}"
  auth_type: "keypair"
  auth:
    keypair: "/home/${USER}/.ssh/id_rsa"
deployment:
  cluster_name: "eloqkv_with_hot_standby_and_voter"
  product: "EloqKV"
  version: "nightly"
  install_dir: "/home/${USER}"
  tx_service:
    tx_host_ports: [172.31.27.125:6379]
    standby_host_ports: [172.31.24.51:6379]
    voter_host_ports: [172.31.19.69:6379]
  log_service:
    nodes:
      - host: 172.31.27.125
        port: 9000
        data_dir:
          - "/home/${USER}/eloqkv_with_hot_standby_and_voter/wal_eloqkv"
    replica: 1
  storage_service:
    rocksdb: Local
