connection:
  username: "${USER}"
  auth_type: "keypair"
  auth:
    keypair: "/home/${USER}/.ssh/id_rsa"
deployment:
  cluster_name: "eloqkv-cluster-singlenode"
  product: "EloqKV"
  version: "latest"
  install_dir: "/mnt/ssd/${USER}/zhouxiao"
  enable_wal: true
  enable_io_uring: false
  enable_tls: false
  cluster_mode: false
  checkpointer_interval: 6000
  tx_service:
    tx_host_ports: [192.168.122.24:6389]
    # enable_cache_replacement: on
    # requirepass: "asd"
    # client_port: 6389
  log_service:
    nodes:
      - host: 192.168.122.25
        port: 9000
        data_dir:
          - "/home/${USER}/eloqkv-cluster-singlenode/wal_eloqkv_9000"
      - host: 192.168.122.25
        port: 9001
        data_dir:
          - "/home/${USER}/eloqkv-cluster-singlenode/wal_eloqkv_9001"
      - host: 192.168.122.25
        port: 9002
        data_dir:
          - "/home/${USER}/eloqkv-cluster-singlenode/wal_eloqkv_9002"
      - host: 192.168.122.25
        port: 9003
        data_dir:
          - "/home/${USER}/eloqkv-cluster-singlenode/wal_eloqkv_9003"
    replica: 2
    bthread_concurrency: 1
  storage_service:
    rocksdb: !LOCAL
  hardware:
    192.168.122.24:
      cpu: 8
      memory: 32768
    192.168.122.25:
      cpu: 4
      memory: 16384
