connection:
  username: "${USER}"
  auth_type: "keypair"
  auth:
    keypair: "/home/${USER}/.ssh/id_rsa"
proxy_service:
  proxy_name: "proxy-1"
  proxy_addrs: [127.0.0.1:6000]
  web_service_ports: [8080]
  install_dir: "/home/${USER}"
  eloqkv_cluster_addr: [127.0.0.1:6379]
  eloqkv_cluster_token: [""]
  eloqkv_cluster_password: [""]