connection:
  username: "${USER}"
  auth_type: "keypair"
  auth:
    keypair: "/home/${USER}/.ssh/id_rsa"
deployment:
  cluster_name: "eloqkv-codis"
  product: "EloqKV"
  version: "latest"
  install_dir: "/home/${USER}"
  tx_service:
    host: [127.0.0.1]
    client_port: 6379
  codis:
    dashboard: 127.0.0.1
    proxy: [127.0.0.1]
  storage_service:
    cassandra:
      host: [127.0.0.1]
      kind: !Internal
        mirror: "https://download.eloqdata.com"
        version: "4.1.3"
