connection:
  username: "${USER}"
  auth_type: "keypair"
  auth:
    keypair: "${CLUSTER_MGR_HOME}/ed25519"
deployment:
  cluster_name: "demo-sql"
  product: "EloqSQL"
  version: "latest"
  install_dir: "${CLUSTER_MGR_HOME}"
  port:
    cs_conn: 3316
    monograph_port:
      start: 8000
      end: 8009
  log_service:
    nodes:
      - host: 127.0.0.1
        port: 9000
        data_dir:
          - "/tmp/logDisk_demoSQL"
    replica: 1
  tx_service:
    host:
      - 127.0.0.1
  storage_service:
  monitor:
    data_dir: ""
    monograph_metrics:
      path: "/mono_metrics"
      port: 18081
    prometheus:
      download_url: "https://d143xau9fe26d8.cloudfront.net/others/prometheus-2.42.0.linux-amd64.tar.gz"
      port: 9500
      host: 127.0.0.1
    grafana:
      download_url: "https://d143xau9fe26d8.cloudfront.net/others/grafana-9.3.6.linux-amd64.tar.gz"
      port: 3301
      host: 127.0.0.1
    node_exporter: "https://d143xau9fe26d8.cloudfront.net/others/node_exporter-1.5.0.linux-amd64.tar.gz"
    node_exporter_port: 9200
    mysql_exporter: "https://d143xau9fe26d8.cloudfront.net/others/mysqld_exporter-0.14.0.linux-amd64.tar.gz"
    mysql_exporter_port: 9300
    cassandra_collector:
      mcac_agent: "https://d143xau9fe26d8.cloudfront.net/others/datastax-mcac-agent-0.3.4-4.1-beta1.tar.gz"
      mcac_port: 9103
  hardware:
    127.0.0.1:
      cpu: 2
      memory: 2048
