connection:
  username: "mono"
  auth_type: "keypair"
  auth:
    keypair: "/home/$USER/.ssh/id_rsa"
deployment:
  install_image: "file:///home/ubuntu/monographdb-release.tar.gz"
  cluster_name: "mono-poc"
  install_dir: "/data1/opt"
  port:
    mysql_port: 3300
    monograph_port:
      start: 8100
      end: 8200
  mono_service:
    host:
      - localhost
  storage_service:
    cassandra:
      download_url: "https://archive.apache.org/dist/cassandra/4.1-rc1/apache-cassandra-4.1-rc1-bin.tar.gz"
      storage_cluster: "mono-cass-cluster"
      host:
        - localhost
#    dynamodb:
#      access_key_id: "",
#      secret_key: ""
#      region: "XXXX",
#      endpoint: "";