[local]
eloq_data_path=${OVERRIDE}
ip=${OVERRIDE}
port=${OVERRIDE}
checkpointer_interval=${OVERRIDE}
enable_data_store=${OVERRIDE}
enable_wal=${OVERRIDE}
enable_io_uring=${OVERRIDE}
enable_cache_replacement=${OVERRIDE}
cluster_mode=${OVERRIDE}
core_number=${OVERRIDE}
event_dispatcher_num=${OVERRIDE}
node_memory_limit_mb=${OVERRIDE}
[cluster]
ip_port_list=${OVERRIDE}
#standby_ip_port_list=${OVERRIDE}
#voter_ip_port_list=${OVERRIDE}
#node_group_replica_num=${OVERRIDE}
#txlog_service_list=${OVERRIDE}
#txlog_group_replica_num=${OVERRIDE}
[store]
#cass_hosts=${OVERRIDE}
#cass_keyspace=eloqkv
#cass_keyspace_replication=1
#rocksdb_storage_path=${OVERRIDE}

[metrics]
enable_metrics=${OVERRIDE}
