[mariadb]
plugin_maturity=experimental
datadir=${OVERRIDE}
lc_messages_dir=${OVERRIDE}
plugin_dir=${OVERRIDE}
max_connections=2000
core_file
skip-log-bin
port=${OVERRIDE}
performance_schema=OFF
socket=${OVERRIDE}
plugin_load_add=ha_eloq
thread_handling=pool-of-threads
#thread_pool_size
thread_pool_max_threads=4
thread_pool_dedicated_listener=1
# eloq engine specific parameter.
eloq
eloq_local_ip=${OVERRIDE}
eloq_ip_list=${OVERRIDE}
eloq_keyspace_name=eloqsql
eloq_kv_storage=dynamo
eloq_dynamodb_region=${OVERRIDE}
eloq_dynamodb_endpoint=${OVERRIDE}
eloq_aws_access_key_id=${OVERRIDE}
eloq_aws_secret_key=${OVERRIDE}



