global:
  scrape_interval: 5s
  evaluation_interval: 5s

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
 - "alert.rules" # Path relative to Prometheus CWD or absolute path

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
#alerting:
#  alertmanagers:
#    - scheme: http
#      static_configs:
#        - targets:
#            - 'alertmanager:9093'