[local]
path=data
ip=${OVERRIDE}
port=${OVERRIDE}
core_number=${SET_FOR_ME}
event_dispatcher_num=${SET_FOR_ME}
node_memory_limit_mb=${SET_FOR_ME}
checkpoint_interval=60
enable_data_store=none
enable_wal=none
[cluster]
# ip_port_list
# txlog_service_list
# txlog_group_replica_num
[store]
#cass_hosts
#cass_keyspace=eloqkv
[metrics]
enable_metrics=false
