[local]
path=data
ip=${OVERRIDE}
port=${OVERRIDE}
core_number=${SET_FOR_ME}
event_dispatcher_num=${SET_FOR_ME}
node_memory_limit_mb=${SET_FOR_ME}
checkpoint_interval=60
skip_kv=true
skip_wal=true
[cluster]
# ip_port_list
# txlog_service_list
# txlog_group_replica_num
[store]
# cass_hosts
[metrics]
enable_metrics=false
