[tasks.rustc-version-nightly]
toolchain = "nightly-2022-12-12"
command = "rustc"
args = ["--version"]

[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
CARGO_MAKE_CRATE_IS_WORKSPACE = true
[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.test]
command = "cargo"
args = ["test", "--tests"]
dependencies = ["clippy"]

[tasks.build_eloqctl]
command = "cargo"
args = ["build", "--package", "cluster_mgr", "--release"]
dependencies = ["format", "generate_proto"]

[tasks.devtools_build]
command = "cargo"
args = ["build", "--package", "devtools", "--release"]
dependencies = ["format"]

[tasks.rest_api_build]
command = "cargo"
args = ["build", "--package", "rest_api", "--release"]
dependencies = ["format"]

[tasks.clippy]
command = "cargo"
args = ["clippy", "--all-targets", "--all-features", "--", "-D", "warnings"]

[tasks.devtools_pkg]
script = '''
#!/bin/bash
MONO_DIST_DIR="mono_devtools_dist"
WORKING_DIR=${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}
echo "build mono_devtools package working_dir="${WORKING_DIR}
TARGET="$WORKING_DIR"/target/release/devtools
function build_package() {
  mkdir -p "$MONO_DIST_DIR" && mkdir -p "$MONO_DIST_DIR"/config
  cp -r $WORKING_DIR/src/devtools/config/* "$MONO_DIST_DIR/config"
  cp "$TARGET" "$MONO_DIST_DIR"
}
build_package
'''
dependencies = ["devtools_build"]

[tasks.rest_api_pkg]
script = '''
#!/bin/bash
WORKSPACE_DIR=${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}
TARGET_DIR=${CARGO_TARGET_DIR:-${WORKSPACE_DIR}/target}
PKG_DIR=${ELOQCTL_PKG_DIR:-eloqctl}
mkdir -p "${PKG_DIR}/bin"
cp ${TARGET_DIR}/release/rest_api "${PKG_DIR}/bin/"
'''
dependencies = ["rest_api_build", "pkg_eloqctl"]

[tasks.pkg_eloqctl]
script = '''
#!/bin/bash
WORKSPACE_DIR="${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}"
TARGET_DIR=${CARGO_TARGET_DIR:-${WORKSPACE_DIR}/target}
CLUSTER_MGR_RELEASE=${TARGET_DIR}/release/cluster_mgr
echo "pkg_eloqctl.workspace = ${WORKSPACE_DIR}"
PKG_DIR=${ELOQCTL_PKG_DIR:-eloqctl}
mkdir -p "${PKG_DIR}/bin"
cd "${PKG_DIR}"
${WORKSPACE_DIR}/version.sh > version 2>/dev/null || true
cp -r ${WORKSPACE_DIR}/src/cluster_mgr/config ./
cp -r ${WORKSPACE_DIR}/tests ./
cd bin
cp "$CLUSTER_MGR_RELEASE" ./
ln -sfn cluster_mgr eloqctl 2>/dev/null || true
'''
dependencies = ["generate_proto", "build_eloqctl"]


[tasks.generate_proto]
command = "cargo"
args = ["check", "--package", "cluster_mgr"]
