{
 "title": "Overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "node_id",
    "query": {
     "query": "label_values({node_id=~\".+\"}, node_id)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(mysql_up, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current TPS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_handlers_total{instance=~\"$host\", handler=~\"commit|rollback\"}[5s]) or irate(mysql_global_status_handlers_total{instance=~\"$host\", handler=~\"commit|rollback\"}[5s]))",
     "legendFormat": "Current TPS"
    }
   ]
  },
  {
   "title": "Current QPS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_queries{instance=~\"$host\"}[5s]) or irate(mysql_global_status_queries{instance=\"$host\"}[5s]))",
     "legendFormat": "Current QPS"
    }
   ]
  },
  {
   "title": "Buffer Pool Size",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (node_id) (memory_limit{node_id=~\"$node_id\"})",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  { "title": "TPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "TPS (total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(tx_processed_total{node_id=~\"$node_id\"}[$__rate_interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "TPS (per Node)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(tx_processed_total{node_id=~\"$node_id\"}[$__rate_interval])) by (node_id)",
     "legendFormat": "node: {{node_id}} "
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "MySQL TPS (total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_handlers_total{instance=~\"$host\", handler=~\"commit|rollback\"}[$__interval]) or irate(mysql_global_status_handlers_total{instance=~\"$host\", handler=~\"commit|rollback\"}[$__interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "MySQL TPS (per Node)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "sum by (instance) (rate(mysql_global_status_handlers_total{instance=~\"$host\", handler=~\"commit|rollback\"}[$__interval]) or irate(mysql_global_status_handlers_total{instance=~\"$host\", handler=~\"commit|rollback\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "TX Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "TX Latency (total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(tx_duration_bucket{node_id=~\"$node_id\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "TX Latency (per Node)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(tx_duration_bucket{node_id=~\"$node_id\"}[$__rate_interval])) by (le, node_id))",
     "legendFormat": "p99, node: {{node_id}} "
    }
   ]
  },
  { "title": "CC Shard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Memory Usage (total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(1 + sum(memory_usage{node_id=~\"$node_id\"})) / (1 + sum(memory_usage{node_id=~\"$node_id\"}))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Memory Usage (per node)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(1 + sum by (node_id)(memory_usage{node_id=~\"$node_id\"})) / (1 + sum by (node_id) (memory_limit{node_id=~\"$node_id\"}))",
     "legendFormat": "node: {{node_id}}"
    }
   ]
  },
  {
   "title": "Cache Hit rate (total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(1 + sum(delta(cache_hits[$__interval]))) / (1 + sum(delta(cache_hits[$__interval])) + sum(delta(cache_miss[$__interval])))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Cache Hit rate (per node)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(1 + sum by(node_id)(delta(cache_hits[$__interval]))) / (1 + sum by(node_id)(delta(cache_hits[$__interval])) + sum by(node_id)(delta(cache_miss[$__interval])))",
     "legendFormat": "node: {{node_id}}"
    }
   ]
  },
  {
   "title": "Run One Round",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process Tx Requests Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le, node_id)(rate(process_tx_requests_duration_bucket[$__rate_interval])))",
       "legendFormat": "p99, node: {{node_id}}"
      }
     ]
    },
    {
     "title": "Process CC Requests Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le, node_id)(rate(process_cc_requests_duration_bucket{node_id=~\"$node_id\"}[$__rate_interval])))",
       "legendFormat": "p99, node: {{node_id}} "
      }
     ]
    },
    {
     "title": "CC Queue Length",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
     "targets": [
      {
       "expr": "avg(cc_queue_length{node_id=~\"$node_id\"}) by (node_id)",
       "legendFormat": "node: {{node_id}} "
      }
     ]
    }
   ]
  }
 ]
}