FROM golang:1.24-bookworm

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        ca-certificates \
        gdb \
        gdbserver \
        iproute2 \
        less \
        lsof \
        procps \
        strace \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace/eloq_waiter
CMD ["sleep", "infinity"]
