use crate::cli::task::cassandra_ctl_task::CassandraCtlTask;
use crate::cli::task::copy_task::CopyTask;
use crate::cli::task::exec_custom_cmd::ExecCustomCommand;
use crate::cli::task::group::{InstallDBTaskGroup, TaskGroup};
use crate::cli::task::monograph_bootstrap_task::MonographInstall;
use crate::cli::task::task_base::{TaskExecutionContext, TaskHost};
use crate::cli::task::upload::upload_task_builder::{upload_tasks, UploadTaskBuilderType};
use crate::cli::SubCommand;
use crate::config::config_base::DeployConfig;
use crate::config::deployment::Product;
use crate::config::DeploymentPackage;
use indexmap::IndexMap;
use tracing::info;

#[async_trait::async_trait]
impl TaskGroup for InstallDBTaskGroup {
    async fn tasks(
        &self,
        cmd_args: SubCommand,
        config: DeployConfig,
    ) -> anyhow::Result<TaskExecutionContext> {
        if config.deployment.tx_service.is_none() {
            return Ok(TaskExecutionContext::dummy());
        }
        let txsrv = config.deployment.tx_service.as_ref().unwrap();
        let conn_user = &config.connection.username;
        let ssh_port = config.connection.ssh_port();
        let install_db_host_string = txsrv.bootstrap_host();
        let install_db_host = TaskHost::Remote {
            user: conn_user.clone(),
            port: ssh_port as usize,
            hosts: install_db_host_string,
        };
        info!(
            "InstallDBTaskGroup The bootstrap node is ={:?}",
            install_db_host
        );
        let install_cmd = SubCommand::Install {
            cluster: config.clone().deployment.cluster_name,
        };
        let mut barrier = vec![];
        let mut executable = IndexMap::new();
        if let Some(cass) = &config.deployment.storage_service.cassandra {
            if cass.internal().is_some() {
                let upload_cass_config_task =
                    upload_tasks(UploadTaskBuilderType::CassConf, &config);
                barrier.push(upload_cass_config_task.len());
                executable.extend(upload_cass_config_task);
                if let Some(monitor) = config.deployment.monitor.as_ref() {
                    if let Some(mcac_collector) = &monitor.cassandra_collector {
                        let install_dir = config.install_dir();
                        let update_http_port_cmd = mcac_collector.update_http_port_cmd(install_dir);
                        let cassandra_hosts = config.get_host_list(DeploymentPackage::Storage);
                        let update_http_port_task = ExecCustomCommand::build_task_by_host(
                            update_http_port_cmd,
                            &config,
                            cassandra_hosts,
                            None,
                        );
                        barrier.push(update_http_port_task.len());
                        executable.extend(update_http_port_task);
                    }
                }
                let cassandra_start = CassandraCtlTask::from_config(install_cmd, &config);
                barrier.extend(CassandraCtlTask::start_barrier(cassandra_start.len()));
                executable.extend(cassandra_start);
            }
        }
        // Bootstrap
        let monograph_install = MonographInstall::from_config(&config, install_db_host);
        barrier.push(monograph_install.len());
        executable.extend(monograph_install);

        if txsrv.product == Product::EloqSQL {
            if txsrv.host.len() > 1 {
                // download data generated by bootstrap
                let (fetch_id, fetch_task) = CopyTask::fetch_datafarm(&config);
                executable.insert(fetch_id, fetch_task);
                barrier.push(1);
                // dispatch data generated by bootstrap
                let upload_data_dir_task = upload_tasks(UploadTaskBuilderType::DataDir, &config);
                barrier.push(upload_data_dir_task.len());
                executable.extend(upload_data_dir_task);
            }
            // rm -rf cc_ng/ tx_log/
            let txsrv_home = config.deployment.tx_srv_home();
            let rm_log_data_cmd =
                format!("rm -rf {txsrv_home}/datafarm/cc_ng {txsrv_home}/datafarm/tx_log",);
            let rm_log_data_task_instance =
                ExecCustomCommand::from_config(&cmd_args, "rm_log", rm_log_data_cmd, &config);
            barrier.push(rm_log_data_task_instance.len());
            executable.extend(rm_log_data_task_instance);
        }

        if config.deployment.codis.is_some() {
            let upload_codis_task = upload_tasks(UploadTaskBuilderType::Codis, &config);
            barrier.push(upload_codis_task.len());
            executable.extend(upload_codis_task);
        }

        Ok(TaskExecutionContext {
            task_group: cmd_args.as_ref().to_string(),
            barrier: Some(barrier),
            executable,
        })
    }
}
