{
 "title": "Monograph Overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "monograph_server",
    "label": "Monograph Server",
    "query": {
     "query": "label_values(memory_limit, instance)"
    }
   },
   {
    "name": "mysql_exporter",
    "label": "MySQL Exporter",
    "query": {
     "query": "label_values(mysql_up, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current TPS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(mysql_processed_tx_total{instance=~\"$monograph_server\"}[5s]))",
     "legendFormat": "Current TPS"
    }
   ]
  },
  {
   "title": "Current QPS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(mysql_processed_query_total{instance=~\"$monograph_server\"}[5s]))",
     "legendFormat": "Current QPS"
    }
   ]
  },
  {
   "title": "Buffer Pool Size",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (memory_limit{instance=~\"$monograph_server\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Max Connections",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (mysql_max_connections{instance=~\"$monograph_server\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (mysql_connection_count{instance=~\"$monograph_server\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "TPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "TX Service TPS (total)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(tx_processed_total{instance=~\"$monograph_server\"}[$__rate_interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "TX Service TPS (per Node)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance)(rate(tx_processed_total{instance=~\"$monograph_server\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "MySQL TPS (total)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(mysql_processed_tx_total{instance=~\"$monograph_server\"}[$__rate_interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "MySQL TPS (per Node)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(mysql_processed_tx_total{instance=~\"$monograph_server\"}[5s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "TX Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "TX Service TX Latency (total)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le)(rate(tx_duration_bucket{instance=~\"$monograph_server\"}[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "TX Service TX Latency (per Node)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, instance)(rate(tx_duration_bucket{instance=~\"$monograph_server\"}[$__rate_interval])))",
     "legendFormat": "p99, node: {{instance}}"
    }
   ]
  },
  {
   "title": "MySQL TX Latency (total)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le)(rate(mysql_tx_duration_bucket{instance=~\"$monograph_server\"}[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "MySQL TX Latency (per Node)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, instance)(rate(mysql_tx_duration_bucket{instance=~\"$monograph_server\"}[$__rate_interval])))",
     "legendFormat": "p99, node: {{instance}}"
    }
   ]
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Memory Usage (total)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(1 + sum(memory_usage{instance=~\"$monograph_server\"})) / (1 + sum(memory_limit{instance=~\"$monograph_server\"}))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Memory Usage (per node)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(1 + sum by (instance)(memory_usage{instance=~\"$monograph_server\"})) / (1 + sum by (instance) (memory_limit{instance=~\"$monograph_server\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Cache Hit Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "Slice Cache Hit rate (total)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(1 + sum(delta(cache_hit_or_miss_total{type=\"hits\", instance=~\"$monograph_server\"}[$__rate_interval]))) / (1 + sum(delta(cache_hit_or_miss_total{type=\"hits\", instance=~\"$monograph_server\"}[$__rate_interval])) + sum(delta(cache_hit_or_miss_total{type=\"miss\",instance=~\"$monograph_server\"}[$__rate_interval])))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Slice Cache Hit rate (per node)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(1 + sum by(instance)(delta(cache_hit_or_miss_total{type=\"hits\", instance=~\"$monograph_server\"}[$__rate_interval]))) / (1 + sum by(instance)(delta(cache_hit_or_miss_total{type=\"hits\",instance=~\"$monograph_server\"}[$__rate_interval])) + sum by(instance)(delta(cache_hit_or_miss_total{type=\"miss\", instance=~\"$monograph_server\"}[$__rate_interval])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Busy Round", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "Busy Round Active TXs Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (instance) (rate(busy_round_active_tx_count{instance=~\"$monograph_server\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Busy Round Processed CC Requests Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (instance) (rate(busy_round_processed_cc_request_count{instance=~\"$monograph_server\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Busy Round Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, instance)(rate(busy_round_duration_bucket{instance=~\"$monograph_server\"}[$__rate_interval])))",
     "legendFormat": "p99, node: {{instance}}"
    }
   ]
  },
  {
   "title": "Empty Round Ratio",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "empty_round_ratio{core_id=\"0\"}",
     "legendFormat": "node: {{instance}}"
    }
   ]
  },
  { "title": "Cassandra", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 } },
  {
   "title": "Load Slice Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(cass_load_slice_duration_bucket{instance=~\"$monograph_server\"}[$__rate_interval])))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Load Slice Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, instance) (rate(cass_load_slice_duration_bucket{instance=~\"$monograph_server\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flush Records to Base Table",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (rate(cass_flush_rows_count{type=\"base\", instance=~\"$monograph_server\"}[$__rate_interval]))",
     "legendFormat": "total {{table_type}}"
    }
   ]
  },
  {
   "title": "Flush Records to Base Table",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(cass_flush_rows_count{type=\"base\", instance=~\"$monograph_server\"}[$__rate_interval]))",
     "legendFormat": "{{instance}} {{table_type}}"
    }
   ]
  },
  {
   "title": "Flush Records to Archive Table",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (rate(cass_flush_rows_count{type=\"archive\", instance=~\"$monograph_server\"}[$__rate_interval]))",
     "legendFormat": "total {{table_type}}"
    }
   ]
  },
  {
   "title": "Flush Records to Archive Table",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(cass_flush_rows_count{type=\"archive\", instance=~\"$monograph_server\"}[$__rate_interval]))",
     "legendFormat": "{{instance}} {{table_type}}"
    }
   ]
  },
  { "title": "Remote Request Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 140 } },
  {
   "title": "Remote Requests Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, type) (rate(remote_request_duration_bucket{instance=~\"$monograph_server\"}[$__rate_interval])))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "On Fly Requests Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (type)(remote_request_on_fly_count{instance=~\"$monograph_server\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Remote Requests Metrics For Each Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 151 },
   "collapsed": true,
   "panels": [
    {
     "title": "Remote Requests Latency For Each Node",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 160 },
     "repeat": "monograph_server",
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le, type, instance) (rate(remote_request_duration_bucket{instance=~\"$monograph_server\"}[$__rate_interval])))",
       "legendFormat": "{{instance}} {{type}}"
      }
     ]
    },
    {
     "title": "On Fly Requests Count For Each Node",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 160 },
     "repeat": "monograph_server",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (type, instance)(remote_request_on_fly_count{instance=~\"$monograph_server\"})",
       "legendFormat": "{{instance}} {{type}}"
      }
     ]
    }
   ]
  }
 ]
}