workspace = "/Users/pangzhenzhou/Downloads/workspace/"

[compile.download]
protobuf = { url = "https://github.com/protocolbuffers/protobuf/releases/download/v3.17.3/protobuf-cpp-3.17.3.tar.gz", build = '''
#!/bin/bash
cd  ${MONOGRAPH_WORKSPACE_DIR}/monograph/third_party/protobuf-3.17.3
pwd
./configure
make -j$(nproc)
make check
sudo make install
''' }

[compile.git]
brpc = { git = "https://github.com/apache/incubator-brpc.git", third_party = true, build = '''
#!/bin/bash
cd  ${MONOGRAPH_WORKSPACE_DIR}/monograph/third_party/brpc
sh config_brpc.sh --headers=/usr/local/include --libs=/usr/local/lib --cc=clang --cxx=clang++
make -j8
''' }
braft = { git = "https://github.com/baidu/braft.git", build = '''
#!/bin/bash
cd  ${MONOGRAPH_WORKSPACE_DIR}/monograph/third_party/braft
sed -i '' 's/libbrpc.a//g' CMakeLists.txt
mkdir -p bld && cd bld
cmake ../ -DOPENSSL_ROOT_DIR="/opt/homebrew/opt/openssl@1.1"
make -j8
''' }
catch2 = { git = "https://github.com/catchorg/Catch2.git", branch = "v2.x", build = '''
#!/bin/bash
cd  ${MONOGRAPH_WORKSPACE_DIR}/monograph/third_party/catch2
''' }
aws = { git = "https://github.com/aws/aws-sdk-cpp.git", options = ["--recurse-submodules"], build = '''
#!/bin/bash
cd  ${MONOGRAPH_WORKSPACE_DIR}/monograph/third_party/aws
mkdir -p bld && cd bld
cmake ../ -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=./output/ -DBUILD_SHARED_LIBS=OFF -DFORCE_SHARED_CRT=OFF -DBUILD_ONLY=dynamodb
make -j8
make install
''' }
log_service = { git = "git@github.com:monographdb/log_service.git" }
tx_service = { git = "git@github.com:monographdb/tx_service.git" }
monograph = { git = "git@github.com:monographdb/monographdb_engine_for_mariadb.git" }
cass = { git = "https://github.com/datastax/cpp-driver.git" }
mariadb = { git = "git@github.com:monographdb/mariadb.git", branch = "monograph-10.6.5" }
[monograph]
storage = "cassandra"