jobs:
  - name: centos7
    serial: true
    plan:
      - in_parallel:
          limit: 2
          steps:
            - get: waiter_src
            - get: image_centos7
      - task: install-test
        image: image_centos7
        file: waiter_src/concourse/task_test.yaml
  - name: centos8
    serial: true
    plan:
      - in_parallel:
          limit: 2
          steps:
            - get: waiter_src
            - get: image_centos8
      - task: install-test
        image: image_centos8
        file: waiter_src/concourse/task_test.yaml
  - name: rocky9
    serial: true
    plan:
      - in_parallel:
          limit: 2
          steps:
            - get: waiter_src
            - get: image_rocky9
      - task: install-test
        image: image_rocky9
        file: waiter_src/concourse/task_test.yaml

  - name: ubuntu18
    serial: true
    plan:
      - in_parallel:
          limit: 2
          steps:
            - get: waiter_src
            - get: image_ubuntu1804
      - task: install-test
        image: image_ubuntu1804
        file: waiter_src/concourse/task_test.yaml
  - name: ubuntu20
    serial: true
    plan:
      - in_parallel:
          limit: 2
          steps:
            - get: waiter_src
            - get: image_ubuntu2004
      - task: install-test
        image: image_ubuntu2004
        file: waiter_src/concourse/task_test.yaml
  - name: ubuntu22
    serial: true
    plan:
      - in_parallel:
          limit: 2
          steps:
            - get: waiter_src
            - get: image_ubuntu2204
      - task: install-test
        image: image_ubuntu2204
        file: waiter_src/concourse/task_test.yaml
  - name: ubuntu24
    serial: true
    plan:
      - in_parallel:
          limit: 2
          steps:
            - get: waiter_src
            - get: image_ubuntu2404
      - task: install-test
        image: image_ubuntu2404
        file: waiter_src/concourse/task_test.yaml

resources:
  - name: waiter_src
    type: git
    icon: github
    source:
      branch: main
      uri: git@github.com:monographdb/monograph_waiter.git
      private_key: ((git-key))

  - name: image_centos7
    type: registry-image
    source:
      username: monographdb
      password: 
      repository: monographdb/waiter-test-centos7
  - name: image_centos8
    type: registry-image
    source:
      username: monographdb
      password: 
      repository: monographdb/waiter-test-centos8
  - name: image_rocky9
    type: registry-image
    source:
      username: monographdb
      password: 
      repository: monographdb/waiter-test-rocky9
  - name: image_ubuntu1804
    type: registry-image
    source:
      username: monographdb
      password: 
      repository: monographdb/waiter-test-ubuntu18
  - name: image_ubuntu2004
    type: registry-image
    source:
      username: monographdb
      password: 
      repository: monographdb/waiter-test-ubuntu20
  - name: image_ubuntu2204
    type: registry-image
    source:
      username: monographdb
      password: 
      repository: monographdb/waiter-test-ubuntu22
  - name: image_ubuntu2404
    type: registry-image
    source:
      username: monographdb
      password: 
      repository: monographdb/waiter-test-ubuntu24
