workspace = "/tmp/monograph_workspace"
initialize_script = '''
#!/bin/bash
rm -rf ${MONOGRAPH_WORKSPACE_DIR}/monograph/datafarm/data_0/
mkdir -p ${MONOGRAPH_WORKSPACE_DIR}/monograph/datafarm/data_0
config_file_name=`ls ${MONOGRAPH_WORKSPACE_DIR}/monograph/etc/ | head -1`
echo ${config_file_name}
config_file_dir=${MONOGRAPH_WORKSPACE_DIR}/monograph/etc/${config_file_name}
${MONOGRAPH_WORKSPACE_DIR}/monograph/install/scripts/mysql_install_db --defaults-file=${config_file_dir} \
 --basedir=${MONOGRAPH_WORKSPACE_DIR}/monograph/install \
 --datadir=${MONOGRAPH_WORKSPACE_DIR}/monograph/datafarm/data_0 \
 --plugin-dir=${MONOGRAPH_WORKSPACE_DIR}/monograph/install/lib/plugin
 '''
[compile.download]
protobuf = { url = "https://github.com/protocolbuffers/protobuf/releases/download/v3.17.3/protobuf-cpp-3.17.3.tar.gz", build = '''
#!/bin/bash
cd  ${MONOGRAPH_WORKSPACE_DIR}/monograph/third_party/protobuf-3.17.3
echo 'build protobuf'
pwd
./configure
make -j$(nproc)
make check
sudo make install
sudo ldconfig
''' }

[compile.git]
brpc = { git = "https://github.com/apache/incubator-brpc.git", build = '''
#!/bin/bash
brpc_dir=${MONOGRAPH_WORKSPACE_DIR}/monograph/third_party/brpc
echo 'build brpc'
cd  ${brpc_dir}
pwd
rm -rf ${brpc_dir}/build/*
cmake -B build
cmake --build build -j5
sudo cp -r ${brpc_dir}/build/output/include/* /usr/include/
sudo cp ${brpc_dir}/build/output/lib/* /usr/lib/
sudo ldconfig
''' }
braft = { git = "https://github.com/baidu/braft.git", build = '''
#!/bin/bash
braft_dir=${MONOGRAPH_WORKSPACE_DIR}/monograph/third_party/braft
cd  ${braft_dir}
pwd
mkdir -p bld && rm -rf ./bld/* && cd bld
cmake .. && make -j8
sudo cp -r ${braft_dir}/bld/output/include/* /usr/include/
sudo cp ${braft_dir}/bld/output/lib/* /usr/lib/
sudo ldconfig
''' }
catch2 = { git = "https://github.com/catchorg/Catch2.git", branch = "v2.x", build = '''
#!/bin/bash
cd  ${MONOGRAPH_WORKSPACE_DIR}/monograph/third_party/catch2
pwd
echo 'build catch2'
mkdir -p bld && rm -rf ./bld/* && cd bld
cmake .. -DCMAKE_INSTALL_PREFIX=/usr/ -DCATCH_BUILD_EXAMPLES=OFF -DBUILD_TESTING=OFF
cmake --build . -j4
sudo cmake --install .
sudo ldconfig
''' }
aws = { git = "https://github.com/aws/aws-sdk-cpp.git", options = ["--recurse-submodules"], build = '''
#!/bin/bash
aws_cpp_sdk_dir=${MONOGRAPH_WORKSPACE_DIR}/monograph/third_party/aws
cd ${aws_cpp_sdk_dir}
echo 'build aws'
pwd
mkdir -p bld && rm -rf bld/* && cd bld
cmake ../ -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=./output/ -DBUILD_SHARED_LIBS=OFF -DFORCE_SHARED_CRT=OFF -DBUILD_ONLY=dynamodb
make -j8
make install
sudo cp -r ${aws_cpp_sdk_dir}/bld/output/include/* /usr/include/
sudo cp -r ${aws_cpp_sdk_dir}/bld/output/lib/* /usr/lib/
sudo ldconfig
''' }
log_service = { git = "git@github.com:monographdb/log_service.git" }
tx_service = { git = "git@github.com:monographdb/tx_service.git" }
monograph = { git = "git@github.com:monographdb/monographdb_engine_for_mariadb.git" }
cass = { git = "https://github.com/datastax/cpp-driver.git" }
mariadb = { git = "git@github.com:monographdb/mariadb.git", branch = "monograph-10.6.5", build = '''
#!/bin/bash
cd ${MONOGRAPH_WORKSPACE_DIR}/monograph/source/mariadb
echo 'build MonographDB'
pwd
mkdir -p bld && rm -rf ./bld/* && cd bld
cmake ../ -DCMAKE_INSTALL_PREFIX="${MONOGRAPH_WORKSPACE_DIR}/monograph/install" -DCMAKE_BUILD_TYPE=Debug \
 -DPLUGIN_{HANDLERSOCKET,ROCKSDB,ARIA,ARCHIVE,CVS,FEDERATEDX,TOKUDB,MROONGA,OQGRAPH,CONNECT,PERFSCHEMA,SPIDER,SPHINX,HEAP,MYISAMMRG,SEQUENCE}=NO \
 -DINSTALL_MYSQLTESTDIR="" \
 -DCMAKE_CXX_FLAGS_DEBUG="${CMAKE_CXX_FLAGS_DEBUG} -Wno-error" -DMYSQL_MAINTAINER_MODE=OFF -DWITH_SSL=system -DWITH_DEBUG=1
cmake --build . --config Debug -j4
cmake --install . --config Debug
''' }
rocksdb = { git = "https://github.com/facebook/rocksdb.git", build= '''
#!/bin/bash
rocksdb_dir=${MONOGRAPH_WORKSPACE_DIR}/monograph/source/rocksdb
cd ${rocksdb_dir}
echo 'build rocksdb'
export PORTABLE=1
make clean && make -j4 shared_lib && sudo make install-shared
sudo ldconfig
'''}
[monograph]
storage = "cassandra"
