{
 "title": "MonoSQL Overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "monosql_server",
    "label": "MonoSQL Server",
    "query": {
     "query": "label_values({job=\"monosql-service\"},  instance)"
    }
   },
   {
    "name": "mysql_exporter",
    "label": "MySQL Exporter",
    "query": {
     "query": "label_values(mysql_up, instance)"
    }
   },
   {
    "name": "read_request",
    "label": "Read Request",
    "query": {
     "query": "label_values({job=\"monosql-service\"},  type)\n"
    }
   },
   {
    "name": "write_request",
    "label": "Write Request",
    "query": {
     "query": "label_values({job=\"monosql-service\"},  type)\n"
    }
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current TPS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_handlers_total{handler=~\"commit|rollback\", instance=~\"$mysql_exporter\"}[5s]) or irate(mysql_global_status_handlers_total{handler=~\"commit|rollback\", instance=~\"$mysql_exporter\"}[5s]))",
     "legendFormat": "Current TPS"
    }
   ]
  },
  {
   "title": "Current QPS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_queries{instance=~\"$mysql_exporter\"}[5s]) or irate(mysql_global_status_queries{instance=\"$mysql_exporter\"}[5s]))",
     "legendFormat": "Current QPS"
    }
   ]
  },
  { "title": "TPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "MySQL TPS (total)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_handlers_total{handler=~\"commit|rollback\", instance=~\"$mysql_exporter\"}[$__rate_interval]) or irate(mysql_global_status_handlers_total{handler=~\"commit|rollback\", instance=~\"$mysql_exporter\"}[$__rate_interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "MySQL TPS (per Node)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(mysql_global_status_handlers_total{instance=~\"$mysql_exporter\", handler=~\"commit|rollback\"}[$__rate_interval]) or irate(mysql_global_status_handlers_total{instance=~\"$mysql_exporter\", handler=~\"commit|rollback\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Requests Count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Read Requests Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (type)(rate(dynamo_request_total{instance=~\"$monosql_server\", type=~\"$read_request\"}[$__rate_interval]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Write Requests Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (type)(rate(dynamo_request_total{instance=~\"$monosql_server\", type=~\"$write_request\"}[$__rate_interval]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Request Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Read Requests Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 31 },
   "repeat": "read_request",
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, type, instance) (rate(dynamo_request_duration_bucket{type=~\"$read_request\", instance=~\"$monosql_server\"}[$__rate_interval])))",
     "legendFormat": "{{instance}} {{type}}"
    }
   ]
  },
  {
   "title": "Write Requests Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 41 },
   "repeat": "write_request",
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le, type, instance) (rate(dynamo_request_duration_bucket{type=~\"$write_request\", instance=~\"$monosql_server\"}[$__rate_interval])))",
     "legendFormat": "{{instance}} {{type}}"
    }
   ]
  }
 ]
}